# Change these first
owner: peposhh
repo: upptime

sites:
  - name: Cinemark Chilee
    url: https://promociones.cinemark.cl/
  - name: Wikipedia
    url: https://es.wikipedia.org/
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co




status-website:
  baseUrl: https://peposhh.github.io/uppTime/
